### ISSUE TITLE
7.6, 8.7 pass by value/copy/reference

### ISSUE THREAD

**Issue by ybakos** [shiffman/LearningProcessing#8]
There are some problems (inaccuracies) with the way pass-by-value and pass-by-reference are presented in the text. First, I recognize that this is a topic that is "more advanced" than the student should be, so I understand the approach of simplifying the concepts.

7.6
_but will not be the case when we learn about objects in the next chapter._
This is incorrect because chapter 8 is incorrect. Objects, and all things in Java, are pass by value. The fact that an object variable is a reference to an object does not change the fact that a copy of the reference is passed to functions. I would simplify this last phrase as _but is not quite the same with objects, which we will learn about in the next chapter_.

8.7
_With objects, this is not the case, and the result is a bit more intuitive. If changes are made to an object after it is passed into a function, those changes will affect that object used anywhere else throughout the sketch. This is known as pass by reference since instead of a copy, a reference to the actual object itself is passed into the function._
This paragraph is wrong, but I feel like there are only two solutions: either simplify this in the main copy as just _With objects, this is not the case: if changes are made to an object after it is passed into a function, those changes will affect that object used anywhere else throughout the sketch_ and provide details about object variables being references in the sidebar; or delve into how objects are represented in memory and so on. One of the best illustrations for this concept is in the Head First Java book. However, in keeping with the spirit of your book, I would simplify this concept, removing the incorrect statement, and perhaps address the "why" in a gray sidebar box like you did in a few other places.

**Comment by shiffman** [comment]
Ok, I am finally getting around to these fixes.  I like the idea of a sidebar but managed to squeeze the chapter 8 section into one paragraph which now reads:

In <a data-type="xref" href="#functions">#functions</a>, we showed how when a primitive value (integer, float, etc.) is passed in a function, a copy is made (known as <em>pass by value</em>. With objects, this is not the case, and the result is a bit more intuitive. If changes are made to an object after it is passed into a function, those changes will affect that object used anywhere else throughout the sketch.  In Java, this is strangely still an example of <em>pass by value</em>, the difference is that a copy of a <em>reference</em> to the object is passed rather than a copy of the object itself.  You can think of a reference as the address in memory where the object's data is stored.  So while that address is copied there is still only one object and so any changes to that object affect both variables.

@ybakos would love any thoughts on the above if you have a minute!  Closing this issue for now.

**Comment by ybakos** [comment]
"With objects, this is not the case..."

I would change that to say something besides "this is not the case," because the following sentences contradict that. (Reader: Uh... so is it the case or is it not the case?)

Maybe just something like:

In #functions, we showed how when a primitive value (integer, float, etc.) is passed *to* a function, a copy of the value is made (known as pass by value*)*. With objects, this process is less intuitive.

**Comment by shiffman** [comment]
Ok, rewritten again now:

<p>In <a data-type="xref" href="#functions">#functions</a>, we showed how when a primitive value (integer, float, etc.) is passed in a function, a copy of the variable is made and the original variable remains the same no matter what happens in the function.  This is known as <em>pass by value</em>. With objects, things work a bit differently.  If changes are made to an object after it is passed into a function, those changes will affect the original object.  Instead of copying the object and passing it into the function, a copy of a <em>reference</em> to the object is passed rather.  You can think of a reference as the address in memory where the object's data is stored.  So while there are in fact two distinct variables holding on their own value, that value is simply an address pointing to only one object.  And so any changes to that object affect both variables.</p>

I am also going to add a diagram which I think will help make it more clear.

**Comment by ybakos** [comment]
That's pretty good! Two minor quibbles:
- first sentence: passed _into_ a function (same as in the remainder of the paragraph)
- delete "rather"

**Comment by shiffman** [comment]
Thanks, changed!
